// Google Ads mock — fields grouped by reporting use-case, templates with coverage
const FIELDS = [
  // Performance
  { id: 'impressions', label: 'Impressions', type: 'metric', group: 'performance', popular: true },
  { id: 'clicks', label: 'Clicks', type: 'metric', group: 'performance', popular: true },
  { id: 'cost_micros', label: 'Cost (micros)', type: 'metric', group: 'performance' },
  { id: 'spend', label: 'Spend', type: 'metric', group: 'performance', popular: true },
  { id: 'ctr', label: 'CTR', type: 'metric', group: 'performance' },
  { id: 'avg_cpc', label: 'Avg. CPC', type: 'metric', group: 'performance' },
  { id: 'avg_cpm', label: 'Avg. CPM', type: 'metric', group: 'performance' },
  { id: 'search_impr_share', label: 'Search Impression Share', type: 'metric', group: 'performance' },
  { id: 'date', label: 'Date', type: 'dimension', group: 'performance', popular: true },
  { id: 'campaign_name', label: 'Campaign Name', type: 'dimension', group: 'performance', popular: true },
  { id: 'campaign_id', label: 'Campaign ID', type: 'dimension', group: 'performance' },
  { id: 'ad_group_name', label: 'Ad Group Name', type: 'dimension', group: 'performance' },
  { id: 'ad_group_id', label: 'Ad Group ID', type: 'dimension', group: 'performance' },
  { id: 'customer_id', label: 'Customer ID', type: 'dimension', group: 'performance', popular: true },
  { id: 'account_name', label: 'Account Name', type: 'dimension', group: 'performance' },

  // Conversion
  { id: 'conversions', label: 'Conversions', type: 'metric', group: 'conversion', popular: true },
  { id: 'conversions_value', label: 'Conversions Value', type: 'metric', group: 'conversion' },
  { id: 'all_conversions', label: 'All Conversions', type: 'metric', group: 'conversion' },
  { id: 'all_conversions_value', label: 'All Conversions Value', type: 'metric', group: 'conversion' },
  { id: 'cost_per_conversion', label: 'Cost per Conversion', type: 'metric', group: 'conversion' },
  { id: 'conversion_rate', label: 'Conversion Rate', type: 'metric', group: 'conversion' },
  { id: 'roas', label: 'ROAS', type: 'metric', group: 'conversion' },
  { id: 'view_through_conversions', label: 'View-through Conversions', type: 'metric', group: 'conversion' },
  { id: 'conversion_action', label: 'Conversion Action', type: 'dimension', group: 'conversion' },
  { id: 'conversion_category', label: 'Conversion Category', type: 'dimension', group: 'conversion' },

  // Audience
  { id: 'age_range', label: 'Age Range', type: 'dimension', group: 'audience' },
  { id: 'gender', label: 'Gender', type: 'dimension', group: 'audience' },
  { id: 'device', label: 'Device', type: 'dimension', group: 'audience' },
  { id: 'geo_country', label: 'Country', type: 'dimension', group: 'audience' },
  { id: 'geo_region', label: 'Region', type: 'dimension', group: 'audience' },
  { id: 'geo_city', label: 'City', type: 'dimension', group: 'audience' },
  { id: 'audience_segment', label: 'Audience Segment', type: 'dimension', group: 'audience' },
  { id: 'household_income', label: 'Household Income', type: 'dimension', group: 'audience' },

  // Creative & Keywords
  { id: 'ad_id', label: 'Ad ID', type: 'dimension', group: 'creative' },
  { id: 'ad_name', label: 'Ad Name', type: 'dimension', group: 'creative' },
  { id: 'ad_type', label: 'Ad Type', type: 'dimension', group: 'creative' },
  { id: 'headline', label: 'Headline', type: 'attribute', group: 'creative' },
  { id: 'final_url', label: 'Final URL', type: 'attribute', group: 'creative' },
  { id: 'keyword_text', label: 'Keyword', type: 'dimension', group: 'creative' },
  { id: 'match_type', label: 'Match Type', type: 'dimension', group: 'creative' },
  { id: 'quality_score', label: 'Quality Score', type: 'metric', group: 'creative' },
];

const GROUPS = [
  { id: 'performance', label: 'Performance', subtitle: 'Spend, clicks, impressions over time' },
  { id: 'conversion', label: 'Conversion & ROI', subtitle: 'Conversions, value, ROAS' },
  { id: 'audience', label: 'Audience & Geography', subtitle: 'Demographics, location, device' },
  { id: 'creative', label: 'Creative & Keywords', subtitle: 'Ads, keywords, quality' },
];

const TEMPLATES = [
  {
    id: 'campaign_performance',
    name: 'Campaign Performance',
    description: 'Daily campaign-level spend, clicks and impressions.',
    label: 'Custom',
    type: 'Global',
    level: 'Campaign',
    granularity: 'Daily',
    fields: ['date', 'customer_id', 'campaign_id', 'campaign_name', 'impressions', 'clicks', 'spend', 'cost_micros', 'ctr', 'avg_cpc', 'avg_cpm'],
  },
  {
    id: 'ad_group_performance',
    name: 'Ad Group Performance',
    description: 'Ad group breakdown of performance metrics.',
    label: 'Custom',
    type: 'Global',
    level: 'Ad Group',
    granularity: 'Daily',
    fields: ['date', 'customer_id', 'campaign_id', 'campaign_name', 'ad_group_id', 'ad_group_name', 'impressions', 'clicks', 'spend', 'cost_micros', 'ctr', 'avg_cpc'],
  },
  {
    id: 'campaign_conversions',
    name: 'Campaign Conversions',
    description: 'Conversion metrics with spend at the campaign level.',
    label: 'Prebuilt',
    type: 'Global',
    level: 'Campaign',
    granularity: 'Daily',
    fields: ['date', 'customer_id', 'campaign_id', 'campaign_name', 'spend', 'conversions', 'conversions_value', 'all_conversions', 'all_conversions_value', 'cost_per_conversion', 'conversion_rate', 'roas'],
  },
  {
    id: 'conversion_actions',
    name: 'Conversion Actions',
    description: 'Per-conversion-action breakdown including view-through.',
    label: 'Custom',
    type: 'Global',
    level: 'Campaign',
    granularity: 'Daily',
    fields: ['date', 'customer_id', 'campaign_id', 'campaign_name', 'conversion_action', 'conversion_category', 'conversions', 'conversions_value', 'view_through_conversions'],
  },
  {
    id: 'demographics',
    name: 'Demographics',
    description: 'Performance split by age and gender.',
    label: 'Prebuilt',
    type: 'Global',
    level: 'Campaign',
    granularity: 'Daily',
    fields: ['date', 'customer_id', 'campaign_id', 'campaign_name', 'age_range', 'gender', 'household_income', 'impressions', 'clicks', 'spend', 'conversions'],
  },
  {
    id: 'geo_performance',
    name: 'Geographic Performance',
    description: 'Country, region and city level performance.',
    label: 'Prebuilt',
    type: 'Global',
    level: 'Campaign',
    granularity: 'Daily',
    fields: ['date', 'customer_id', 'campaign_id', 'campaign_name', 'geo_country', 'geo_region', 'geo_city', 'impressions', 'clicks', 'spend', 'conversions'],
  },
  {
    id: 'device_performance',
    name: 'Device Performance',
    description: 'Performance and conversions split by device.',
    label: 'Custom',
    type: 'Global',
    level: 'Campaign',
    granularity: 'Daily',
    fields: ['date', 'customer_id', 'campaign_id', 'campaign_name', 'device', 'impressions', 'clicks', 'spend', 'ctr', 'conversions', 'conversions_value'],
  },
  {
    id: 'audience_segments',
    name: 'Audience Segments',
    description: 'Audience segment level performance.',
    label: 'Custom',
    type: 'Global',
    level: 'Ad Group',
    granularity: 'Daily',
    fields: ['date', 'customer_id', 'campaign_id', 'ad_group_id', 'audience_segment', 'impressions', 'clicks', 'spend', 'conversions'],
  },
  {
    id: 'ad_performance',
    name: 'Ad Performance',
    description: 'Creative-level performance with headlines and URLs.',
    label: 'Prebuilt',
    type: 'Global',
    level: 'Ad',
    granularity: 'Daily',
    fields: ['date', 'customer_id', 'campaign_id', 'ad_group_id', 'ad_id', 'ad_name', 'ad_type', 'headline', 'final_url', 'impressions', 'clicks', 'spend', 'conversions'],
  },
  {
    id: 'keyword_performance',
    name: 'Keyword Performance',
    description: 'Keyword-level performance with quality and match type.',
    label: 'Custom',
    type: 'Global',
    level: 'Keyword',
    granularity: 'Daily',
    fields: ['date', 'customer_id', 'campaign_id', 'ad_group_id', 'keyword_text', 'match_type', 'quality_score', 'impressions', 'clicks', 'spend', 'avg_cpc', 'conversions'],
  },
  {
    id: 'search_impression_share',
    name: 'Search Impression Share',
    description: 'Auction insights and impression share at the campaign level.',
    label: 'Prebuilt',
    type: 'Global',
    level: 'Campaign',
    granularity: 'Daily',
    fields: ['date', 'customer_id', 'campaign_id', 'campaign_name', 'search_impr_share', 'impressions', 'clicks'],
  },
  {
    id: 'account_summary',
    name: 'Account Summary',
    description: 'Account-level rollup. Lightweight daily totals.',
    label: 'Prebuilt',
    type: 'Global',
    level: 'Account',
    granularity: 'Daily',
    fields: ['date', 'customer_id', 'account_name', 'impressions', 'clicks', 'spend', 'conversions', 'conversions_value'],
  },
];

const POPULAR = ['impressions', 'clicks', 'spend', 'conversions', 'campaign_name', 'date', 'customer_id'];

window.IMPROVADO_DATA = { FIELDS, GROUPS, TEMPLATES, POPULAR };
